if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi
if [ -f /etc/skel/.bashrc ]; then
    . /etc/skel/.bashrc
fi
if [ -f ~/.bash_local ]; then
    . ~/.bash_local
fi
if [ -f ~/.nvm/nvm.sh ]; then
    . ~/.nvm/nvm.sh
    nvm alias default 0.8
fi
if [ -f ~/.rbenv ]; then
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
fi
alias tm=tmux
export PATH=$HOME/.nodebrew/current/bin:$PATH
