:set number
:syntax on
:set tabstop=4
:set expandtab
au BufNewFile,BufRead *.psgi set filetype=perl
au BufNewFile,BufRead /etc/nginx/* set ft=nginx 
au BufNewFile,BufRead *gitconfig* set ft=gitconfig
