source "https://rubygems.org"
#gemspec

gem 'chef'
gem 'knife-solo'
gem 'berkshelf'
gem 'chefspec'

gem 'rspec'
gem 'simplecov', :require => false, :group => :test

gem 'serverspec'

#gem 'simplecov-rcov'

