# -*- encoding: utf-8 -*-
require 'rubygems'
require 'rake'
 
require 'rspec/core'
require 'rspec/core/rake_task'
 
task :default => :spec
 


desc "Run all specs in spec directory"
RSpec::Core::RakeTask.new do |task|
  task.pattern = "**/spec/*_spec.rb"
  task.rspec_opts = '--color'
end
